### ISSUE TITLE
Python: program is hanging when deleting nmslib object in child thread

### ISSUE THREAD

**Issue by Aljaksandr** [searchivarius/nmslib#291] opened 2018-02-16 13:46 UTC
Hi there.
Suppose I've found a bug in multithreaded usage of nmslib objects. When attempting to delete an instance of nmslib index in a child thread the program freezes. The code to reproduce that bug:
```python
import nmslib
import numpy
from threading import Thread
import time


class nmslib_index:
    def __init__(self):
        self.index_nms = None
        self.reinit()

    def reinit(self):
        print("Start reinitialisation")
        if self.index_nms:
            print("     Start releasing memory")
            nmslib.freeIndex(self.index_nms)
            print("     Deleting of object")
            del self.index_nms

        print("     Reinitialisation")
        self.index_nms = nmslib.init(method='hnsw', space='l2', dtype=nmslib.DistType.FLOAT)
        dat = numpy.random.randn(100, 128).astype(numpy.float32)
        ids = range(100)
        print("     Adding new data")
        self.index_nms.addDataPointBatch(dat, ids)
        print("     Index creating")
        self.index_nms.createIndex({'post': 2}, print_progress=True)
        print("Done!")


def reinit(index):
    index.reinit()

if __name__ == '__main__':
    index = nmslib_index()

    print("<<<Main thread reinitialisation>>>")
    reinit(index)

    print("<<<Child thread reinitialisation>>>")
    th1 = Thread(target=reinit, daemon=True, args=(index, ))

    th1.start()
    th1.join()
```

The output:
```
Start reinitialisation
     Reinitialisation
     Adding new data
     Index creating

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*****************************************************Done!
<<<Main thread reinitialisation>>>
Start reinitialisation
     Start releasing memory
     Deleting of object
     Reinitialisation
     Adding new data
     Index creating

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*****************************************************Done!
<<<Child thread reinitialisation>>>
Start reinitialisation
     Start releasing memory
     Deleting of object
```

**Comment by searchivarius** [comment] 2018-02-16 14:01
Hi, one can have only one library object per program.

**Comment by Aljaksandr** [comment] 2018-02-16 14:43
Yes, but there is only one object which each time before reinitialization is released and deleted.

**Comment by Aljaksandr** [comment] 2018-02-16 14:46
There is no problem to reinitialize (with deleting of nmslib object instance) in main thread. But the problem is in attempting to do that in child thread

**Comment by benfred** [comment] 2018-02-16 17:58
Thanks @Aljaksandr ! I've managed to replicate the problem, I love bug reports with simple working examples =).

Looking at stack traces and it looks like both threads are trying to acquire the GIL, and deadlocked because of it:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x00007fff5f884cee libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #1: 0x00007fff5f9c1662 libsystem_pthread.dylib`_pthread_cond_wait + 732
    frame #2: 0x00000001001cfa83 python`PyThread_acquire_lock_timed + 275
    frame #3: 0x00000001001d8737 python`acquire_timed + 727

* thread #2
  * frame #0: 0x00007fff5f884cee libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #1: 0x00007fff5f9c1662 libsystem_pthread.dylib`_pthread_cond_wait + 732
    frame #2: 0x0000000100153e41 python`take_gil + 417
    frame #3: 0x0000000100154196 python`PyEval_AcquireThread + 22
    frame #4: 0x0000000101d6c75d nmslib.cpython-36m-darwin.so`pybind11::gil_scoped_acquire::gil_scoped_acquire(this=0x000070000443cf88) at pybind11.h:1641 [opt]
    frame #5: 0x0000000101d6d662 nmslib.cpython-36m-darwin.so`similarity::PythonLogger::log(this=0x000000010064bcb0, severity=LIB_DEBUG, file=<unavailable>, line=<unavailable>, function=<unavailable>, message="Destroying Index") at nmslib.cc:332 [opt]
    frame #6: 0x0000000101d83a1f nmslib.cpython-36m-darwin.so`LogItem::~LogItem(this=0x000070000443d0f0) at logging.h:94 [opt]
```

The issue is that I've added a debug log statement here https://github.com/searchivarius/nmslib/blob/master/python_bindings/nmslib.cc#L351 (for tracking down another issue), and that this gets directed to a python logger - which requires the GIL.

However, the 2nd thread already should have ownership of the GIL and is erroneously trying to reacquire it again using py::gil_scoped_acquire. 
I think this is an issue with pybind11 and gil_scoped_acquire being called on threads created from python (as fixed here https://github.com/pybind/pybind11/pull/1211 ).

It looks like this is fixed in the next version of pybind11, but since we're supporting pybind > 2.0 - I'm going to put in a workaround here.

**Comment by benfred** [comment] 2018-02-16 18:20
Fix is here https://github.com/searchivarius/nmslib/pull/292 - and I verified with the test script here that this works. Thanks again!

**Comment by searchivarius** [comment] 2018-02-18 22:57
Thank you @benfred ! @Aljaksandr I have pushed all the changes to the master and uploaded a new PiPy version. Could you try an updated one?

**Comment by benfred** [comment] 2018-02-19 00:55
Changes look like they are working for me! Previously the build on ann-benchmarks was hanging on nmslib (https://travis-ci.org/erikbern/ann-benchmarks/builds/342479957), but with this fix pushed out it finished succesfully (https://travis-ci.org/erikbern/ann-benchmarks/builds/343165955).

**Comment by Aljaksandr** [comment] 2018-02-19 06:56
Thank you @benfred, @searchivarius. Looks like this bug is fixed. Works well in my environment ) Many thanks again.

**Closed** 2018-02-19 13:31 UTC
