### ISSUE TITLE
Version 1.6.3 - space and method functionality?

### ISSUE THREAD

**Issue by mmcneill** [searchivarius/nmslib#238] opened 2017-09-18 20:47 UTC
I recently moved to version 1.6.3 (python) and have some questions about available functionality for using sparse vectors with the small_world_rand/hnsw methods and the ability to save/load an index.  

* Can I use the cosinesimil_sparse space with small_world_rand and/or hnsw?
* Can I save/load an index built using either combination of cosinesimil_sparse/small_world_rand or cosinesimil_sparse/hnsw?  I used to be able to save and load a cosinesimil_sparse/small_world_rand index, but since updating to 1.6.3, I can only save (tying to load gives me a segmentation fault).  I am unable to even successfully save a cosinesimil_sparse/hnsw index.
* What are the options for possible space_params, index_params, and query_params?  I used to use NN, initIndexAttempts, and indexThreadQty with cosinesimil_sparse/small_world_rand, but now it seems initIndexAttempts is no more. Documentation for the other parameter types (including which ones can be used with different methods and versions of nmslib) appears to be non-existent.  

Ideally I would like to use hnsw, but I cannot find any good documentation about what is or is not allowed (sparse vectors, saving/loading indices, param options) for this version. Any guidance would be much appreciated.

**Comment by searchivarius** [comment] 2017-09-19 02:28
Hi @mmcneill thank you for the interest!
1) Yes
2) save/load with small_world, but not with hnsw. It's bloody shame that I haven't fixed this yet. Seems to become a priority.
3) space_params are empty for simple spaces. 
Index params: reasonable values for NN to try 15-50. Then search parameter efSearch would range from say 10 to 1000 (again need to check empirically how it works).
For HNSW, M would also range from 15 to 50 (or a bit larger value). Similar range for efSearch: 10 to 1000. You need to skip_optimized_index=1 unless you use dense cosine or l2.
There are a couple more parameters to try:
delaunay_type it's 2 by default, but other values to try are 0 and 3.
Values of post = 1 or 2 can improve retrieval speed albeit at the cost of doubling indexing time.

**Comment by mmcneill** [comment] 2017-09-19 22:42
Thanks for your quick response, @searchivarius!  I appreciate you sharing the parameter information.  

I am still having issues loading an index using small_world_rand.  I have attached a simple example that leads to a segmentation fault in the final line.  Any idea where I am going wrong?  

```python

import nmslib
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

names = ['JOHN SMITH', 'MARY JOHNSON', 'JANE DOE', 
         'BOB JACKSON', 'JOHN DOE', 'LEWIS BROWN']

# create sparse shingles matrix
vectorizer = CountVectorizer(analyzer='char', ngram_range=(2,2), 
                             dtype=np.float32, decode_error='replace')
names_sparse_matrix = vectorizer.fit_transform(names)

# CREATE INDEX 
# ------------

space_type = 'cosinesimil_sparse'
method_name = 'small_world_rand'

index = nmslib.init(space  = space_type,
                    method = method_name,
                    data_type = nmslib.DataType.SPARSE_VECTOR,
                    dtype = nmslib.DistType.FLOAT)

# batch load data points
index.addDataPointBatch(data = names_sparse_matrix, 
                        ids = np.arange(len(names), dtype=np.int32))

# build and save index
index_params = {'NN' : 15}
index.createIndex(index_params)
index.saveIndex(method_name + "_sparse.index")

# make sure it works
near_neighbors = index.knnQueryBatch(queries=names_sparse_matrix[1:2], k=2, num_threads=2)

# SET UP LOADED INDEX 
# -------------------

reloaded_index = nmslib.init(space  = space_type,
                             method = method_name,
                             data_type = nmslib.DataType.SPARSE_VECTOR,
                             dtype = nmslib.DistType.FLOAT)

reloaded_index.addDataPointBatch(data = names_sparse_matrix, 
                                 ids = np.arange(len(names), dtype=np.int32))

reloaded_index = reloaded_index.loadIndex(method_name + '_sparse.index') 
# SEGMENTATION FAULT

```

**Comment by searchivarius** [comment] 2017-09-20 00:50
[test1.py.gz](https://github.com/searchivarius/nmslib/files/1316233/test1.py.gz)
Hmmm, will it work if you install a version that is currently in the master?
I slightly modified your script (see attached) to make it query from loaded index and it works on my machine.
**Important:** when you build the old version, please, make sure you delete the old installation files, e.g., for Python **2.7** on Ubuntu 16:
```
rm -rf /usr/local/lib/python2.7/dist-packages/nmslib-1.6.3-py2.7-linux-x86_64.egg/
```
BTW, which OS, Python, and compiler do you use?

Thank you!

**Comment by searchivarius** [comment] 2018-01-15 03:25
I am closing this one, b/c I cannot reproduce the issue.

**Closed by searchivarius** 2018-01-15 03:25 UTC
